### ISSUE TITLE
d3_queue Uncaught Error

### ISSUE THREAD

**Issue by staircaseblog** [d3/d3-queue#54]
Hi, i had a working setup with d3 queue. For some reason it does not work any more and i have no clue after two days. I updated to the latest version. Exactly the same behaviour. To some extent i believe it has nothing to do with d3_queue itself. It just happens to it.

The code bails on first use of defer. Nothing is done by defer, it seems to fail immediately. If i am going in the browser console and instantiate a new instance it works. 

(http://uhvauerr.de/ --> login with defaults --> select any marker --> error)

```js
var lade = function(rahmen, cback){
        var url = "/api/v2/datad3?rahmen=" + rahmen + "&geraet=" + geraet;

        d3.json(url).header('X-Access-Token', token).header('X-Key', user).get(function (error, data) {
            cback(error, data);
        });
    };

    var taskqueue = d3_queue.queue(2);
    var frameurl = "/api/v2/frames?geraet=" + geraet;

    d3.json(frameurl).header('X-Access-Token', token).header('X-Key', user).get(function(error, data){
        $.each(data, function (index, frame) {
            console.log(frame.rahmen);
            taskqueue.defer(lade, frame.rahmen); //<<<<<<<<<<<<<<<<<<<<<<<<ERROR HERE
        });
    });

    taskqueue.awaitAll(function(error, results) {

        //console.log(results);
        var data = [];

        results.forEach(function (c, i, a) {
            console.log(c);
            //c.knoten_id;
            c.datensaetze.forEach(function (d, j, a) {
                d.key = "" + (c.knoten_id) + "_" + d.key; // WORKAROUND Rahmen id sollte vom json file kommen
                data.push(d);
            });
        });

        console.log(data);

        if(data.length != 0) {
            makeGraph(data);
        }
    });
 ```

```
Uncaught Error
c.defer @ d3-queue.min.js:1
(anonymous function) @ VM484:135
n.extend.each @ jquery-2.2.0.min.js:2
(anonymous function) @ VM484:133
(anonymous function) @ d3.js:1899
event @ d3.js:434
respond @ d3.js:1852
```

**Comment by mbostock** [comment]
The issue is that you’ve set your awaitAll callback before deferring your tasks. Specifically, you’re calling `taskqueue.defer` in your d3.json callback, which happens *after* you (synchronously) called `taskqueue.awaitAll`.

You must call *queue*.await or *queue*.awaitAll after any calls to *queue*.defer. This is so that you get one (and exactly one) notification of when your queue of tasks has finished.

In this case, I’d move the construction of the queue into after your d3.json callback.

```js
d3.json(frameurl).header('X-Access-Token', token).header('X-Key', user).get(function(error, data){
  if (error) throw error; // If the initial request fails…
  var taskqueue = d3_queue.queue(2);
  $.each(data, function (index, frame) {
    taskqueue.defer(lade, frame.rahmen)
  });
  taskqueue.awaitAll(function(error, results) {
    if (error) throw error; // If a queued request fails…
    console.log(results);
  });
});
```

**Comment by mbostock** [comment]
(In older versions of d3-queue, this was not enforced, and you probably were receiving multiple await callbacks: once at the beginning with no results, and then repeatedly each time a task finished.)

**Comment by staircaseblog** [comment]
Bullseye. Thanks for instant reply.

2016-01-28 21:27 GMT+01:00 Mike Bostock <notifications@github.com>:
