### ISSUE TITLE
The keyword 'await' is reserved

### ISSUE THREAD

**Issue by jehiah** [d3/d3-queue#55]
Trying to setup [rollup](http://rollupjs.org/) to pull in d3, and i'm running into this error:

```
Error parsing ..../node_modules/d3-queue/src/queue.js: The keyword 'await' is reserved (92:20)
```

**Comment by mbostock** [comment]
Wild guess, but you’re using a version prior to 1.1.0 and f8951de484adffa04df73ae360f547eeb81a0a2c? I recommend upgrading to d3-queue@2.

**Comment by jehiah** [comment]
nope, i'm using 2.0.2, the most current from `npm` and the most current version of `rollup`. `npm list` shows the following:

```
├─┬ d3@4.0.0-alpha.14
│ ├ ....
│ ├── d3-queue@2.0.2
├─┬ rollup@0.25.3
```

**Comment by mbostock** [comment]
Strange, well, this module is built using Rollup, and so is the [D3 4.0 branch](https://github.com/mbostock/d3/tree/4). So I suspect there’s something else going on here.

**Comment by mbostock** [comment]
(Is it possible you have more than one copy of d3-queue in your node_modules?)

**Comment by jehiah** [comment]
nope. If it's helpful i can try to build a reproducible setup

**Comment by mbostock** [comment]
Yeah, if you can give me enough information to reproduce the problem, I will investigate.

**Comment by jehiah** [comment]
https://gist.github.com/jehiah/5e2d2eb4bf9a827406fc should do the trick

```
$ ./run.sh 
...
Error parsing /.../rollup_await_error/node_modules/d3-queue/src/queue.js: The keyword 'await' is reserved (92:20) in /.../rollup_await_error/node_modules/d3-queue/src/queue.js
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

**Comment by mbostock** [comment]
Strange, doesn’t produce an error for me.

**Comment by mbostock** [comment]
But also your main.js doesn’t export anything, so maybe it’s not pulling it the code?

**Comment by mbostock** [comment]
Nope, changing main.js to this produced a valid out.js, but still no error:

```
import * as d3 from "d3";

export default d3;
```

Maybe try `npm cache clean`?

**Comment by mbostock** [comment]
(I noticed a bug in d3 4.0 alpha 14 where two copies of d3-scale were included. That’s fixed in alpha 15, and you should upgrade, but that should be unrelated to this bug.)

**Comment by jehiah** [comment]
strange you see no error. In case it's helpful. I should have also listed this:

```
$ npm -v
3.5.3
$ node -v
v5.4.1
```

I'm probably in over head on this one, as JS isn't my normal cup of tea. If you have any suggestions on a cleaner set of reproducible steps i'm all ears.

I have confirmed that the error is related to this line in `rollup` (which is to say the error goes away if i change `await` to `aawait` to skip the check) but it's unclear where in rollup source that line comes from (probably one of it's build dependencies?) as i only see it in the dist file. Also unclear to me now is if `d3-queue` has a legit use of that keyword and this is actually a rollup bug. 

```
$ ack -C 3 await node_modules/rollup/dist/rollup.js
    this.options = options = getOptions(options);
    this.sourceFile = options.sourceFile;
    this.keywords = keywordRegexp(keywords[options.ecmaVersion >= 6 ? 6 : 5]);
    var reserved = options.allowReserved ? "" : reservedWords$1[options.ecmaVersion] + (options.sourceType == "module" ? " await" : "");
    this.reservedWords = keywordRegexp(reserved);
    var reservedStrict = (reserved ? reserved + " " : "") + reservedWords$1.strict;
    this.reservedWordsStrict = keywordRegexp(reservedStrict);
```

I'll keep digging

**Comment by mbostock** [comment]
I am on npm 3.5.3 and node 5.5.0, but I don’t think that should make a difference…

You might try setting options.sourceType to "module"?

**Comment by jehiah** [comment]
this sounds like it could be caused by ternjs/acorn#365 (acorn being dev/build dependency of `rollup`) which was in the most recent version of acorn

**Comment by mbostock** [comment]
Wouldn’t that imply there is an `import {await} from "foo"` statement somewhere?

**Comment by jehiah** [comment]
From my reading this is a parse time error in acorn as used by `rollup@0.25.3`. Since it's parse time, it's failing on the function in d3-queue stored in a [`await`](https://github.com/d3/d3-queue/blob/master/src/queue.js#L86) variable. Changing that function name removes the error.

This seems to somewhat match the motivations in ternjs/acron#365 and the exception added in ternjs/acron#368  (but it's beyond me to interpret if this is the right behaviour or not).

(I'm still confused as to why you didn't see the same error; do you have a different version of rollup, or a globally installed version of rollup that might be used instead?)

**Comment by mbostock** [comment]
That’s not a variable; it’s a property, and reserved words are fine as properties because [they are not identifiers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_word_usage).

Also, the line referenced points to awaitAll, not await, so I think something else is going on here. Unless Acorn is incorrectly checking property names against reserved words, in which case, a bug should be filed there.

**Comment by mbostock** [comment]
I tried using acorn@2.7.0 to parse d3-queue’s src/queue.js, and it worked fine. So, I don’t have any great ideas.

**Comment by mbostock** [comment]
Can you post the contents of your `rollup_await_error/node_modules/d3-queue/src/queue.js`?

**Comment by jehiah** [comment]
I'm also confused by the line number reference. As i'm learning more here, I agree with the reference you just listed, that `await` should be ok in this usage and so this is a `rollup` and `acorn` bug. I'll try to write an issue there. Still confused though why you don't see the same thing.

my copy of `queue.js` is https://gist.github.com/jehiah/82d5f56191fd6eac1ae0

(also, p.s. thanks for helping troubleshoot this strange issue! I've been happy using d3 for my [annual reports](https://jehiah.cz/14) in the last few years, and am excited to try v4 this time around)

**Comment by mbostock** [comment]
Sorry I wasn’t able to figure out what’s going on here. Thanks for your patience, and I hope this is resolved in Rollup or Acorn.

**Comment by lsbardel** [comment]
Hi, I have the same problem while compiling [giotto](https://github.com/quantmind/giotto) with `d3-queue`.
Did you find what the problem was? This is the [rollup.config.js](https://github.com/quantmind/giotto/blob/master/rollup.config.js) I use.
Maybe the `es2015-rollup` preset is causing the issue?

**Comment by elaval** [comment]
I was having a similar issue ("keyword await is reserved ..." for d3-queue), in some cases and others not.

Finally I realised that it was a conflict with babel. In my case it was solved, configuring "exclude:'node_modules/**' in rollup.config.js:

```
export default {
  (...)
  plugins: [
    (...)
    babel({
      exclude: 'node_modules/**'
    })
  ],
  (...)
};

```

**Comment by lsbardel** [comment]
This is the fix I'm using from the rollup issue reported above.
And it works.

```
export default {
   (...)
   acorn: {
        allowReserved: true
    }
}
```
