### ISSUE TITLE
queue.js has errors when processed with ES2015

### ISSUE THREAD

**Issue by MichelFloyd** [d3/d3-queue#58]
[See babel](http://babeljs.io/repl/#?evaluate=true&presets=es2015%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&code=(function()%20%7B%0A%20%20var%20slice%20%3D%20%5B%5D.slice%3B%0A%0A%20%20function%20queue(parallelism)%20%7B%0A%20%20%20%20var%20q%2C%0A%20%20%20%20%20%20%20%20tasks%20%3D%20%5B%5D%2C%0A%20%20%20%20%20%20%20%20started%20%3D%200%2C%20%2F%2F%20number%20of%20tasks%20that%20have%20been%20started%20(and%20perhaps%20finished)%0A%20%20%20%20%20%20%20%20active%20%3D%200%2C%20%2F%2F%20number%20of%20tasks%20currently%20being%20executed%20(started%20but%20not%20finished)%0A%20%20%20%20%20%20%20%20remaining%20%3D%200%2C%20%2F%2F%20number%20of%20tasks%20not%20yet%20finished%0A%20%20%20%20%20%20%20%20popping%2C%20%2F%2F%20inside%20a%20synchronous%20task%20callback%3F%0A%20%20%20%20%20%20%20%20error%20%3D%20null%2C%0A%20%20%20%20%20%20%20%20await%20%3D%20noop%2C%0A%20%20%20%20%20%20%20%20all%3B%0A%0A%20%20%20%20if%20(!parallelism)%20parallelism%20%3D%20Infinity%3B%0A%0A%20%20%20%20function%20pop()%20%7B%0A%20%20%20%20%20%20while%20(popping%20%3D%20started%20%3C%20tasks.length%20%26%26%20active%20%3C%20parallelism)%20%7B%0A%20%20%20%20%20%20%20%20var%20i%20%3D%20started%2B%2B%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20t%20%3D%20tasks%5Bi%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20a%20%3D%20slice.call(t%2C%201)%3B%0A%20%20%20%20%20%20%20%20a.push(callback(i))%3B%0A%20%20%20%20%20%20%20%20%2B%2Bactive%3B%0A%20%20%20%20%20%20%20%20t%5B0%5D.apply(null%2C%20a)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%0A%20%20%20%20function%20callback(i)%20%7B%0A%20%20%20%20%20%20return%20function(e%2C%20r)%20%7B%0A%20%20%20%20%20%20%20%20--active%3B%0A%20%20%20%20%20%20%20%20if%20(error%20!%3D%20null)%20return%3B%0A%20%20%20%20%20%20%20%20if%20(e%20!%3D%20null)%20%7B%0A%20%20%20%20%20%20%20%20%20%20error%20%3D%20e%3B%20%2F%2F%20ignore%20new%20tasks%20and%20squelch%20active%20callbacks%0A%20%20%20%20%20%20%20%20%20%20started%20%3D%20remaining%20%3D%20NaN%3B%20%2F%2F%20stop%20queued%20tasks%20from%20starting%0A%20%20%20%20%20%20%20%20%20%20notify()%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20tasks%5Bi%5D%20%3D%20r%3B%0A%20%20%20%20%20%20%20%20%20%20if%20(--remaining)%20popping%20%7C%7C%20pop()%3B%0A%20%20%20%20%20%20%20%20%20%20else%20notify()%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20function%20notify()%20%7B%0A%20%20%20%20%20%20if%20(error%20!%3D%20null)%20await(error)%3B%0A%20%20%20%20%20%20else%20if%20(all)%20await(error%2C%20tasks)%3B%0A%20%20%20%20%20%20else%20await.apply(null%2C%20%5Berror%5D.concat(tasks))%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20return%20q%20%3D%20%7B%0A%20%20%20%20%20%20defer%3A%20function()%20%7B%0A%20%20%20%20%20%20%20%20if%20(!error)%20%7B%0A%20%20%20%20%20%20%20%20%20%20tasks.push(arguments)%3B%0A%20%20%20%20%20%20%20%20%20%20%2B%2Bremaining%3B%0A%20%20%20%20%20%20%20%20%20%20pop()%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20return%20q%3B%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20await%3A%20function(f)%20%7B%0A%20%20%20%20%20%20%20%20await%20%3D%20f%3B%0A%20%20%20%20%20%20%20%20all%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20if%20(!remaining)%20notify()%3B%0A%20%20%20%20%20%20%20%20return%20q%3B%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20awaitAll%3A%20function(f)%20%7B%0A%20%20%20%20%20%20%20%20await%20%3D%20f%3B%0A%20%20%20%20%20%20%20%20all%20%3D%20true%3B%0A%20%20%20%20%20%20%20%20if%20(!remaining)%20notify()%3B%0A%20%20%20%20%20%20%20%20return%20q%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%3B%0A%20%20%7D%0A%0A%20%20function%20noop()%20%7B%7D%0A%0A%20%20queue.version%20%3D%20%221.0.7%22%3B%0A%20%20if%20(typeof%20define%20%3D%3D%3D%20%22function%22%20%26%26%20define.amd)%20define(function()%20%7B%20return%20queue%3B%20%7D)%3B%0A%20%20else%20if%20(typeof%20module%20%3D%3D%3D%20%22object%22%20%26%26%20module.exports)%20module.exports%20%3D%20queue%3B%0A%20%20else%20this.queue%20%3D%20queue%3B%0A%7D)()%3B%0A)

> repl: Unexpected token (45:30)
> 
>     function notify() {
>       if (error != null) await(error);
>       else if (all) await(error, tasks);
>       else await.apply(null, [error].concat(tasks));
>     }

**Comment by mbostock** [comment]
You’re using an ancient version (1.0.7, January 2014). The code was rewritten in 1.1.0 (January 2016) fixing this problem, and the latest release is 2.0.3 (March 2016).

**Comment by MichelFloyd** [comment]
My apologies! I was chasing this down from a Meteor package which had incorporated queue-async. Quite a rabbit hole.
