### ISSUE TITLE
.awaitAll calling early

### ISSUE THREAD

**Issue by jcontour** [d3/d3-queue#69]
I'm defining a queue and adding .defer tasks using a loop followed by an .awaitAll, I'm having an issue where the .awaitAll is getting called before all of the tasks have been completed and I'm not sure where the issue lies.

```
var findLatLon = function(loc, callback){
   d3.json("http://maps.googleapis.com/maps/api/geocode/json?address=" + loc + "&sensor=true", 
      function(err, res){
         callback( res['results'][0]['geometry']['location'] )
      })
}

var q = d3.queue();

for (var i = 0; i < locationArray.length; i++){
   q.defer(findLatLon, locationName);
}

q.awaitAll(function(err, res) {
    if (err) throw err;
   console.log("queue done",  res);
});
```

**Comment by mbostock** [comment]
Two problems:

1. You’ve configured the queue with unbounded concurrency, so all of your tasks will start immediately as you register them. You probably want to say `q = d3.queue(1)` instead to serialize the requests.

2. You’re invoking the callback with only the *error* argument, so your task always errors. You probably want to say `callback(err, res)` or similar when invoking the callback.

**Comment by jcontour** [comment]
That fixed the problem, thanks so much!
