### ISSUE TITLE
Cannot catch 422 errors

### ISSUE THREAD

**Issue by russellbits** [d3/d3-queue#71]
I cannot catch any XMLHttpRequest error from the defer method.

    var q = d3.queue();
    q.defer(d3.json, '/data/subpops.json'); // local json file
    q.defer(d3.json, sealRequest); // URL determined elsewhere; can result in 422 error
    q.await(function(error, file1, file2) {
      console.log(error)  // await never executes; this console never fires
      var rings = transformAPI(file2)
    }

The browser simply logs "Failed to load resource: the server responded with a status of 422" but nowhere in defer() or await() am I able to catch this error.

**Comment by git-ashish** [comment]
Where are you importing (using) d3.json from?

**Comment by git-ashish** [comment]
Make sure it is coming from https://github.com/d3/d3-request. I suspect the mandatory callback of the .defer() task is not being invoked.

**Comment by mbostock** [comment]
Sorry, but I’m not able to investigate this without a live test case. If you are willing to post an example to bl.ocks.org or similar I would be happy to take a look. My guess is that the error is outside of the snippet.

**Comment by russellbits** [comment]
Actually, the error can be caught. The matter that ended up causing me problems was that await receives *either* the error or what defer was fetching. If you get an error, none of the other calls will have results. I suppose this is fine, and I created a work-around by creating a second queue inside .await() but I feel like a more robust solution would be if await got an error, but also what calls it could complete.
