### ISSUE TITLE
Uncaught TypeError: d3.queue is not a function D3v5 vanilla

### ISSUE THREAD

**Issue by zrfrank** [d3/d3-queue#73]
# Problem description and reproduction

The D3 library is loaded within `<head>` and in the main script log `d3` object and call `d3.queue`.

Macos High Sierra 10.13.6 and Chrome 67.0.3396.99 (Official Build) (64-bit).

```html
<head>
  <script src="https://d3js.org/d3.v5.js"></script>
</head>
```

```js
document.addEventListener("DOMContentLoaded", () => {
  console.log(d3); 
  d3.queue();
}
```

Chrome console
```
Uncaught TypeError: d3.queue is not a function
    at HTMLDocument.document.addEventListener (main.js:15)
```

The full log including the `d3` object is attached below, and I can't find `queue`. As the installation section stated,

>You can also load directly from d3js.org, either as a standalone library or as part of D3 4.0. AMD, CommonJS, and vanilla environments are supported. In vanilla, a d3 global is exported:

I am wondering. has the `queue` been removed from the `D3 5.0` main library?

[localhost-1533822745479.log](https://github.com/d3/d3-queue/files/2274437/localhost-1533822745479.log)

**Comment by git-ashish** [comment]
From what I know, d3.queue was never a part of main d3 build. You have to include it separately.

**Comment by mbostock** [comment]
Please read the release notes for D3.
